transformationList = list("Difference" = "diff",
                          "Subtract Rolling Median" = "submedian",
                          "Subtract Historical Median" = "subhistmedian",
                          "Subtract cross-sectional Median" = "crossmedian",
                          "% Change" = "perchg",
                          "% Change from Median" = "perchgmedian",
                          "% Change from Std" = "perchgstd",
                          "Z-Score Cross Sectional" = "zscorecross",
                          "Z-Score Longitudinal" = "zscorelong",
                          "Binary (String)" = "binarystring",
                          "Binary (Value)" = "binaryvalue")